dancerfly/django-brambling

brambling/templates/brambling/event/order/shop.html

this seems to work well for the carousels but not the thumbnails

bulk adjust images in shop carousels

---

brambling/templates/brambling/splash.html

Questions:
- Is it a bad idea to copy over the password?
- Can using the login/signup be even more similar and streamlined in the future?
I figured I'd do this while I still had it fresh from #311, since I've been meaning to work on this forever.

copy inputs between signup and login forms on splash

---

brambling/templates/brambling/event/organizer/_form_js.html

Supersedes #317, using @melinath's code.

#311 Prepopulate Check Recipient

---

brambling/migrations/0018_itemoption_remaining_display.py
brambling/models.py
brambling/templates/brambling/event/order/shop.html
brambling/templates/brambling/event/organizer/item_form.html
brambling/templates/brambling/forms/itemoption.html

Lets organizers choose on a per-option basis whether and how they want to display the number available. Even has a fancy collapse in the itemoption editing form!

Remaining display

---

brambling/templates/brambling/event/order/shop.html

restore plus in shop on items without limits

---

brambling/forms/organizer.py
brambling/migrations/0020_auto_20150225_0204.py
brambling/migrations/0021_auto_20150228_1832.py
brambling/models.py
brambling/templates/brambling/_event_list_item.html
brambling/templates/brambling/event/order/shop.html
brambling/templates/brambling/forms/event.html
brambling/templates/brambling/splash.html

Added a facebook URL field and tweaked display of website_url. This request resolves tickets #340 and #276.

Ticket/340 & Ticket/276

---

brambling/models.py
brambling/templates/brambling/invite.html
brambling/templates/brambling/mail/invite_editor_body.html
brambling/templates/brambling/mail/invite_home_body.html
brambling/views/core.py

Resolved #373.
Also slightly improved the email html and made Invite code swear-safe.

Improved invite acceptance process.

---

brambling/templates/brambling/event/organizer/order_detail.html
brambling/urls.py
brambling/views/organizer.py

Implemented admin-facing option to manually send order receipts.

---

brambling/admin/admin.py
brambling/tests/unit/test_utils_payment.py
brambling/utils/payment.py
brambling/views/orders.py
brambling/views/payment.py

Resolved a couple of bugs related to (dwolla) payment processing.
Specifically #370 and #386.

Dwolla fixes

---

brambling/forms/orders.py

Corrected removal of additional items from Attendees.

---

Gemfile.lock
brambling/sass/modules/_layout.sass
brambling/sass/modules/_text.sass
brambling/static/brambling/css/styles.css
brambling/templates/brambling/_event_list-group-item.html
brambling/templates/brambling/_event_list_item.html
brambling/templates/brambling/event/_when.html
brambling/templates/brambling/event/_where.html
brambling/templates/brambling/event/order/_masthead.html
brambling/templates/brambling/event/order/shop.html
brambling/templates/brambling/event/organizer/_nav.html

before | after
----|----
(I had to update the gemfile lock at the same time because the code was out of sync with the versions listed.)

Event detail smallfix

---

brambling/views/orders.py

Corrected workflow for SurveyDataView.

---

brambling/templates/brambling/forms/event.html

Don't trust the diff. Literally just wrapped that table in a table-responsive

closed #366 invite table overflow

---

brambling/templates/brambling/about.html

Added custom forms to features list.

---

brambling/templates/brambling/forms/event.html

Added explanatory text to 'collect housing data' checkbox.

---

brambling/static/brambling/sass/modules/_headings.sass
brambling/templates/brambling/_event_list_item.html
brambling/templates/brambling/dashboard.html
brambling/templates/brambling/organization/detail.html
brambling/views/core.py
brambling/views/organizer.py

Events are now visually in a single feed and the update registration button indicates your registration state:
See #460

Combined upcoming event feed

---

brambling/static/brambling/jquery.formset.js
brambling/templates/brambling/__base.html
brambling/templates/brambling/event/organizer/_item_form.html
brambling/templates/brambling/event/organizer/_item_form_js.html
brambling/templates/brambling/event/organizer/custom_form_form.html

Fixes to Chosen on formsets

---

brambling/migrations/0011_auto_20150603_1708.py
brambling/migrations/0012_customformfield_help_text.py
brambling/models.py
brambling/templates/brambling/event/organizer/__table.html
brambling/templates/brambling/event/organizer/custom_form_form.html
brambling/templates/brambling/forms/customformfield.html
brambling/utils/model_tables.py
brambling/views/organizer.py

Adds support for choice fields (radio, select, checkbox multiple, and select multiple) and field help text. Bam.

Form improvements

---

brambling/forms/organizer.py
brambling/migrations/0015_auto_20150609_0033.py
brambling/migrations/0020_auto_20150609_0033.py
brambling/models.py
brambling/templates/brambling/event/organizer/_form_js.html
brambling/templates/brambling/forms/event.html
brambling/templates/brambling/invite.html
brambling/templates/brambling/mail/invite_event/body.html
brambling/templates/brambling/mail/invite_event/body_inlined.html
brambling/templates/brambling/mail/invite_event/body_plaintext.txt
brambling/templates/brambling/mail/invite_event/subject.txt
brambling/tests/functional/test_event_model.py
brambling/tests/functional/test_invites.py
brambling/urls.py
brambling/views/core.py
brambling/views/orders.py
brambling/views/organizer.py

Resolves #537 (invite-only events). This PR will add a new Invite type, which creates an order for the invited person, and disallow order creation for users via other means – thus making the event invite-only! Remaining bits:

Invite-only events (probably ready)

---

brambling/filters.py
brambling/templates/brambling/event/organizer/__table.html
brambling/utils/model_tables.py

(Replacing columns displaying counts of cart vs. purchased vs. refunded items.)
Resolved ticket #579. Sorry to jump in on this, but I promised an event we'd prioritize it, so I wanna make sure to follow through.

Added column that displays a list of the items attached to an attendee on attendee tables.

---

brambling/views/organizer.py

So somehow this was a thing. Stumbled across it by accident.

Limited item editing within an event to that event's items. o_O

---

brambling/forms/organizer.py
brambling/migrations/0022_auto_20150908_1533.py
brambling/models.py

Event slug uniqueness

---

brambling/filters.py
brambling/forms/organizer.py
brambling/utils/model_tables.py
brambling/utils/timezones.py

See #579 for motivation.
So, this is not quite done yet (I think). But I'm putting the code up here because I can't figure something out with Django's template filters. Specifically the date filter. I'd sort of rather have the date formatting stuff happen in the template, but I wasn't able to get any text to show up when I applied the filter.
If it's not something we care that strongly about, then great. Though it might be worth thinking about adding some date & time specific formatting stuff to `ModelTable` that handles basic human-friendly formatting (e.g. we will probably never want to show microseconds) and maybe also time zone stuff.

Sort orders and attendees by date

---

brambling/forms/organizer.py

This worked when I tested it. I hope it's not too un-django-ish!

Exclude current event (if present) from slug uniqueness check. Refs #594

---

brambling/templates/brambling/dashboard.html

* Moved title and hint into main column instead of above both columns
* Added a block for messages

Dashboard refinements:

---

brambling/forms/orders.py
brambling/templates/brambling/__base.html
brambling/templates/brambling/event/order/attendee_basic_data.html
brambling/templates/brambling/event/order/email.html
brambling/templates/brambling/event/order/survey.html
brambling/templates/brambling/forms/attendee_housing.html
brambling/templates/brambling/forms/customformfield.html
brambling/templates/brambling/forms/discount.html
brambling/templates/brambling/forms/event.html
brambling/templates/brambling/forms/home.html
brambling/templates/brambling/forms/hosting.html
brambling/templates/brambling/forms/rows/bootstrap.html
brambling/templates/brambling/forms/rows/no_label.html
brambling/templates/brambling/forms/signup_row.html
brambling/templates/brambling/organization/event_defaults.html
brambling/templates/brambling/organization/payment.html
brambling/templates/brambling/organization/permissions.html
brambling/templates/brambling/organization/profile.html
brambling/templates/brambling/user/account.html
brambling/templates/brambling/user/billing.html
brambling/templates/brambling/user/profile.html

* Marking optional fields with "(Optional)" instead of required
fields with asterisks. See: http://www.lukew.com/ff/entry.asp?725
* Chosen multiple select placeholder
"Select Some Options" -> "Select all that apply"
* Chosen single select placeholder
"Select an Option" -> "Select one"

Some form UI updates:

---

brambling/templates/brambling/event/organizer/finances.html
brambling/views/utils.py

Turns out the finance CSV changes broke the links to remote charge URLs! This should fix the issue.

Made finances table use Rows so that we can still access the transaction object.

---

brambling/utils/model_tables.py

Attendee table was displaying the total order balance - but something in the query was fucking shit up and showing balances two, three times as large as the actual order balance. Plus, that information doesn't make any sense given the table's focus on the attendee object itself. So I removed that column altogether and instead included how much had been paid for the attendee's items.
Future improvement along these lines: add boolean column for whether there are unconfirmed payments (or with the amount of unconfirmed payments). My only concern is that detecting whether there are unconfirmed payments / how many there are might be a PITA, since transactions are order level. But it can probably be done... as a separate PR.

Improved accuracy of attendee table balances & item lists while reducing query counts.

---

brambling/migrations/0025_auto_20151002_2116.py
brambling/models.py

Increased boughtitem status length to fit 'transferred'

---

brambling/templates/brambling/event/order/__base.html

Get the image url directly.

---

brambling/templates/brambling/event/order/summary.html

Resolved #658. As per discussion there, this should be enough, since all we need to prevent is accidents rather than malicious intent.

Set up disabling of buttons on payment form submission to prevent duplicate payments.

---

.travis.yml
README.rst
brambling/tests/integration/test_dwolla.py
test_project/requirements.txt
test_project/test_project/settings.py

Hypothetical travis-ci support.

---

brambling/tests/functional/test_organizer_views.py
brambling/views/organizer.py
test_project/requirements.txt

Resolved #643. See discussion in #676, which this supersedes.

Added unicode csv support to model table views.

---

brambling/models.py

(that didn't really break anything as it stands, but still.)

Minor tweaks to transaction.refund() to clarify comments and fix some egregious logic errors

---

brambling/static/brambling/brambling.kickoff.js
brambling/templates/brambling/forms/discount.html
brambling/templates/brambling/forms/event.html
brambling/templates/brambling/forms/itemoption.html

Also tweaked discount form to make availability a little more obvious.
Resolved #491.

Set up calendar prepends on date fields (and clocks on time fields.)

---

brambling/forms/organizer.py
brambling/migrations/0035_auto_20151202_1727.py
brambling/models.py
brambling/templates/brambling/_event_list-group-item.html
brambling/templates/brambling/_event_list_item.html
brambling/templates/brambling/about.html
brambling/templates/brambling/event/order/_masthead.html
brambling/templates/brambling/event/order/shop.html
brambling/templates/brambling/event/organizer/_nav.html
brambling/templates/brambling/event/organizer/create.html
brambling/templates/brambling/forms/rows/bootstrap.html
brambling/templates/brambling/pricing.html
brambling/views/organizer.py

Set up org creation directly from event creation. I feel like there must be a ticket open for this but I can't find it right now.
Users without an org will only have the option to create. Other users default to existing org but can toggle between that and creating a new org.

Org creation

---

brambling/templates/brambling/event/order/hosting.html

What it says on the box. Small oversight back in the day.

Updated hosting form to only display custom fields area if there are in fact custom fields.

---

brambling/migrations/0044_auto_20160112_2020.py
brambling/models.py
brambling/templates/brambling/about.html
brambling/templates/brambling/pricing.html

Changed models.py so that Organization.default_application_fee_percent and Event.default_application_fee were now 2.5 instead of 1.5, and also updated about.html and pricing.html in templates/brambling accordingly.

Updated org percentage to 2.5%

---

brambling/templates/brambling/event/order/_use_discount_js.html
brambling/templates/brambling/event/order/shop.html

Resolves #689 by wrapping the discount field in shop.html with a form tag and having _user_discount_js.html refer to the button's 'submit' action.

Changed discount form on shop page so pressing enter would submit the discount.

---

brambling/tests/functional/test_invites.py
brambling/views/core.py

Resolves #743 – thanks, @JCattera

Order create purge

---

brambling/templates/brambling/event/organizer/_header.html

Corrected tooltip placement in event admin header

---

brambling/forms/organizer.py
brambling/models.py

Orders already do this. Resolves an issue reported by an event organizer.

Made default discount codes also use unambiguous chars.

---

brambling/views/core.py

Actually import the thing we are using.

Fix missing transaction import

---

salt/webserver/nginx.conf

Add Strict-Transport-Security header to nginx config.

---

requirements-server.txt
salt/webserver/webproject/webproject/settings.py

Because merge with mailchimp :-(

Switched from Mandrill to Sendgrid.

---

README.rst
requirements.txt

* Fixed broken link in README
* Removed pip from requirements.txt

Minor updates

---

brambling/static/brambling/javascript/components/attendees.ractive.js

Yay scoping issues. Fixes the problem.

Added stepbar steps to attendee scope on attendee selection page

---

salt/circus/circusd.conf

Corrected circusd upstart conf

---

requirements.txt

Lets us get emails in the admin interface
Close #832

Update django-talkback version

---

brambling/models.py
brambling/templates/brambling/event/organizer/registration.html

Shows a warning if check postmark date has passed.
Closes #766

766 check warning

---

brambling/forms/orders.py
brambling/models.py
brambling/templates/brambling/event/order/_attendee_summary.html
brambling/templates/brambling/event/order/transfer.html
brambling/templates/brambling/forms/signup.html
brambling/tests/factories.py
brambling/tests/functional/test_order_views.py
brambling/views/orders.py
brambling/views/user.py

Closes #840 
Closes #850 
* Protected the POST route
* Informs the user and leads them to sign up

Fix unauthenticated transfer 500 and prohibits transfers while payment is pending

---

brambling/models.py
brambling/tests/functional/test_order_model.py

Resolved #841.
TBH I am concerned about this because I thought I had more work to do on it but when I look over it I don't see anything missing... so I think it's all good?

Updated Order.get_summary_data for better transfer handling

---

brambling/tests/functional/test_organizer_views.py
brambling/views/organizer.py

We fucked up. The existing behavior was the intended behavior.

Removed  attendees from table view

---

brambling/templates/brambling/event/order/_pending_transfers_summary.html
brambling/tests/functional/test_invites.py
brambling/utils/invites.py

Closes #598 
Must merge #858 before this one.

Allow transfer cancellation

---

.flake8
.travis.yml
requirements-server.txt

There are some issues with travis conf. This PR resolves them.

Fixes for travis configuration

---

brambling/forms/organizer.py
brambling/templatetags/zenaida.py
brambling/tests/functional/test_mailers.py
brambling/tests/functional/test_order_receipt_mailer.py
brambling/utils/model_tables.py
brambling/views/organizer.py
brambling/views/utils.py

Resolved #917. I copied over the templatetags wholesale because it's a simpler / less risky change than updating all the templates that load the zenaida tags.

Added zenaida templatetags to brambling

---

Dockerfile
README.rst
bin/docker-entrypoint.sh
docker-compose.yaml

Add configuration files to allow the application and database to run in a Docker container for development.

Docker compose

---

brambling/forms/base.py
brambling/forms/orders.py
brambling/forms/organizer.py

Resolved #919. This is exactly the same code (with linting), and I've updated the import paths that referenced this code from brambling.

Copied zenaida.forms to brambling.forms.base

---

brambling/templates/brambling/__base.html

This PR combines the base templates for zenaida and brambling. Resolved #920.

Combined zenaida base template with brambling base template
