dancerfly/django-brambling

brambling/forms/organizer.py

From the ticket:
There are two issues:
1. The test api fields are not excluded from the form, which means they get blanked every time the form saves.
2. If the "disconnect" boxes are checked, it always manually blanks the non-test fields. Which means that they'll get erased when they shouldn't, and that if the test fields weren't getting blanked, they never could be.
This pull request resolves both issues, resulting in a form that functions as it should.

Corrected event update form support for live/test apis. Resolved #329.

---

brambling/sass/modules/_modals.sass
brambling/sass/styles.sass
brambling/static/brambling/css/styles.css

I'm not sure why this was a problem, since we use the example bootstrap markup, but this does fix it.

closed #375 modal close button

---

Gemfile.lock
brambling/static/brambling/css/styles.css
brambling/templates/brambling/event/order/__base.html
brambling/templates/brambling/event/order/_next_step_button.html
brambling/templates/brambling/event/order/attendee_basic_data.html
brambling/templates/brambling/event/order/attendee_housing.html
brambling/templates/brambling/event/order/email.html
brambling/templates/brambling/event/order/hosting.html
brambling/templates/brambling/event/order/shop.html
brambling/templates/brambling/event/order/summary.html
brambling/templates/brambling/event/order/survey.html
brambling/templates/brambling/layouts/12.html

I updated the layout for all the order pages. In particular:
* The next step button never appears at the top of a page
* A cart button appears up there instead to remind you how many items you are buying
* The cart button prompts a modal that displays all the items in your cart
* The next step button _almost_ always will appear on the bottom right of the page, except when editing an attendee where a user must explicitly choose to save the attendee or cancel
* The next step button is always at the bottom on mobile!
* This whole thing works much better on mobile, I think, though the stepbar still needs love.
There's more that could be done in terms of polish here, but I think it's also ready to go as-is. I'm open to suggestions for this PR or to future polishing tickets.

Checkout relayout

---

brambling/forms/organizer.py
brambling/migrations/0025_order_notes.py
brambling/models.py
brambling/templates/brambling/event/organizer/order_detail.html
brambling/views/organizer.py

Related to #242. Really, I think this should close #242. Adding notes field to attendees requires a much more invasive change, since we don't even have a way to view them in the admin right now.
Part of me wants to prioritize this, since we have a request from an event for notes functionality - but they might be looking for notes on attendee, not on order. Not sure.
This also needs to be added to the model table display, but I didn't want to much up the merge of the #409 branch by creating conflicts... Maybe I shouldn't worry about that, though.

Added 'notes' tab to order management for admins.

---

brambling/forms/organizer.py
brambling/models.py
brambling/templates/brambling/forms/event.html
brambling/templates/brambling/organization/payment.html
brambling/templates/brambling/organization/profile.html

This commit is basically a cleanup of things related to demo organizations. It provides two simple methods – `Organization.is_demo()` and `Event.is_demo()` – which can be used to check whether the organization or event is a demo.
In practical terms, this PR results in a few extra bits of helpful text being displayed, slugs not being modifiable, and new events being set to use test APIs.
It *might* make more sense to handle the demo slug as a setting rather than an attribute on Organization, but this is easier and it's not really ever going to be customized...

Org static slug

---

brambling/templates/brambling/email_confirm.html
brambling/templates/brambling/event/order/shop.html
brambling/templates/brambling/forms/person.html
brambling/templates/brambling/layouts/_messages.html
brambling/views/core.py
brambling/views/orders.py
brambling/views/user.py

Some minor cleanup / improvements to email confirmation behavior. Resolved #362 and #479. Users can now register without confirming their email address, accepting an invitation confirms your address, and invalid tokens give you an informative message & resend link rather than a 404 error.
#246 (claiming old orders) is more involved, so I figured it would be best to keep as a separate ticket.

Email confirmation improvements

---

brambling/models.py
brambling/templates/brambling/event/organizer/finances.html
brambling/views/organizer.py

Resolved #508.
I've tested this; the links seem to work properly for stripe vs. dwolla, test vs. live, and purchase vs. refund.

Added links to remote payment detail pages from finances view.

---

brambling/templates/brambling/event/organizer/finances.html
brambling/tests/functional/test_finance_table.py
brambling/views/organizer.py
brambling/views/utils.py

Puts a button the Finances page that exports what's on the table as a CSV. 
Implementation-wise, it's highly possible this could be more idiomatically Django. My strategy was to make a Python class that controls the formatting logic (which I copied from the template) and call it from the view. In theory this class could also be used to generate the data in the template -- with some tweaking (e.g. generating a link for the order number). 
Possible open questions:
* Button positioning. It doesn't match the Attendees or Orders pages, but is possibly more obvious without all the rest of the controls. My technique here is called "don't mess with CSS until absolutely necessary."
* I might be doing unnecessary work to get the timezone right in `format_timestamp`. The template uses a special …

Allow exporting the Finances table as a CSV

---

brambling/forms/organizer.py

I put `facebook_url` in the `EventForm`'s list of fields and, ta-da, it shows back up on the update/create event forms. 
Also, I did a little history-diving and it's not totally clear to me if this field used to be in the list and was removed, or never was there to begin with. So, I hope its being gone was just an oversight and not something intentional. That is, I'm not totally sure this addition doesn't unexpectedly change something besides the event forms. But I'm fairly sure?

Facebook URL needs to here to be in the form. Refs #575

---

brambling/forms/organizer.py

I think the words start & end got swapped in the validation error message for "Start Date" and "End Date" for events.

Correct validation help text.

---

brambling/templates/404.html
brambling/templates/500.html

See issue #578 for original issue.
Adds a couple options, including the support email, to the 404 and 500 pages. Also includes an explicit link to the home page, in case people don't know what's going on at all. I actually feel like there could be more text here, given that it's highly possible people will encounter these pages via links from external sites (e.g. Dance organizations). If someone clicks, say, an outdated "purchase tickets" link on a totally different website, they could be very confused.
So it might make sense in the future to have more fine-grained errors like "Organization not found" or "Dance event not found" or "Dance event expired" -- maybe these already exist? -- to combat the problem.
But for now, here are some changes that at least make the error pages marginally …

Informative error pages

---

brambling/utils/model_tables.py

Apparently Excel doesn't like to open files that begin with "ID", so
let's change it.

Fix file-format bug from Excel 2003. Refs #558

---

brambling/filters.py
brambling/utils/model_tables.py
brambling/views/organizer.py

This pull request changes the order table to only display orders that have completed transactions (and removes the cart_items field), and changes the attendees table to only display attendees who have bought boughtitems (i.e. exclude folks who are in the process of registering.)
This should address the difficulties that organizers have been having interpreting the tables, by limiting the data to what they actually *need*.

Bought only tables

---

brambling/static/brambling/sass/modules/_menus.sass
brambling/templates/brambling/event/organizer/__table.html
brambling/templates/brambling/event/organizer/finances.html
brambling/views/organizer.py
test_project/requirements.txt

Add a button to export the currently exportable tables into .xlsx format.
The UI is about as simple as possible and could possibly be improved, but I am not really familiar enough with the buttons and controls you have going so it might be inconsistent. Having one button for csv and one for excel could pretty easily be replaced with a dropdown or popup or something else to make it fit in better with what you have or just generally be more user-friendly.

Add Excel file export. Refs #572

---

brambling/templates/brambling/mail/order_receipt/body.html
brambling/templates/brambling/mail/order_receipt/body_inlined.html
brambling/templates/brambling/mail/order_receipt/body_plaintext.txt

Resolved #637. From the ticket:
>Right now, we send order code URLs to anonymous orders and flat URLs to non-anonymous orders. As long as folks stay logged in and never change computers, that's fine. But I think we should actually switch to always sending the code version. If they are logged in, it's just another redirect; if not, they can be routed appropriately and redirected back.

Made order receipts always use order code URLs.

---

brambling/tests/functional/test_invites.py
brambling/views/core.py

Turns out entering an incorrect invite code got you a 500 error. Whoops! This fixes that and adds a test proving so.

Corrected invite accept view behavior on an invalid invite code.

---

brambling/models.py
brambling/tests/functional/test_order_model.py

Right now, get_summary_data operates on bought_items and their related transactions. So if a transaction doesn't have items, it won't display. This is especially problematic if there's a duplicate transaction for some reason (in which case the second transaction won't get any items and won't be displayed, but will still be charged.) This change will preserve current behavior while also displaying item-less transactions for registrants and organizers.

Made sure Order.get_summary_data includes data for all transactions, even if they don't have any items.

---

brambling/static/brambling/sass/modules/_masthead.sass

See #669 
Mostly this is for better compatibility with transparent PNG images.

Ensure a white background for banner images.

---

brambling/templates/brambling/event/organizer/__table.html

What do people think about this as a simple solution to #473? 
The gist of it: if the value of a cell is long, wrap it using django's build-in word wrap filter, then turn off the table's auto-wrapping feature with `white-space: nowrap`, as we are already doing for iterable cells.
This has the advantage of not needing to change the ModelTable code or manually assign widths to specific columns.
The disadvantage, as I see it, is that we may end up having to do the above anyway if we ever want to change to `table-layout: fixed`, which is a CSS property I didn't know much about but does allow for more control over how the table is rendered. But you have to specify the column widths yourself rather than let the browser render them based on the table cell's contents. I have a feeling this …

Manually apply word-wrapping to cells with long values.

---

brambling/static/brambling/sass/modules/_modals.sass

See #431 for example of problem.
All bootstrap buttons seem to have `white-space: nowrap` on them, so it's possible there are other places on the site where lengthy user input could create overflowing text. This pull request does not fix the general case, just this specific modal.

Prevent text overflow for the cart-expired modal popup.

---

brambling/models.py
brambling/tests/functional/test_transaction_model.py

Resolved #686 plus a bit. Basically, corrected Transaction refund-related behavior when Transaction's amount is 0 (for example, a fully-comped item). Includes new tests, oh boy!

Can refund fix

---

brambling/templates/brambling/forms/event.html
brambling/templates/brambling/organization/profile.html

Switched labels for event & org slug fields to "URL" and added a prepend to make clear what the final URL will be. Also added some help text to the org & event website/facebook fields.

Made slug fields more intuitive. Resolved #496.

---

brambling/templates/brambling/event/organizer/_item_form.html
brambling/templates/brambling/event/organizer/custom_form_form.html
brambling/templates/brambling/event/organizer/custom_form_list.html
brambling/templates/brambling/forms/customformfield.html

Resolved #544. Turns out the only organizer forms that displayed these fields were the custom form forms. So I cleaned them up a bit and made them match the item option formsets, resolving this issue along the way.

Hide index / deletion fields

---

brambling/templates/brambling/dashboard.html

I noticed that Rain City Blues can't be found on the dashboard. Turns out it's cause we limit the dashboard to five events because reasons. I don't think we need to do that thing any more.

Lengthened dashboard to show all upcoming events, rather than just 5.

---

brambling/tests/functional/test_order_views.py
brambling/views/orders.py

Apparently comped transactions have just not been getting receipt emails for some reason. I was so sure they were getting them I figured this was more likely a Mandrill bug... but nope! Anyway, fixed now, with tests.

Added email sending for transactions with no balance change.

---

brambling/forms/orders.py
brambling/models.py
brambling/tests/functional/test_order_forms.py

I am fairly certain that these ValueErrors (caused by expired dwolla refresh tokens) could still crop up if a user's token was expired (rather than the organization's) but this at least plugs the one hole (during validation)

Added form handling of ValueErrors that might be raised while attempting to refresh dwolla information.

---

brambling/mail.py
brambling/tests/functional/test_order_receipt_mailer.py

I think as part of #719 the `unconfirmed_check_payments` flag became lost. This brings it back.

Fix unconfirmed check detection in order receipt emails.

---

brambling/api/v1/views.py
brambling/tests/functional/test_api.py

Seems to work okay. Don't have too much to add, here.
Also adds tests for this ItemOption taken endpoint.

Excluded transferred items from the taken counts.  Fixed #683

---

brambling/api/v1/views.py
brambling/templates/brambling/mail/invite_editor/subject.txt
brambling/templates/brambling/mail/invite_event/subject.txt
brambling/templates/brambling/mail/invite_org_editor/subject.txt
brambling/templates/brambling/mail/invite_transfer/subject.txt
brambling/templates/brambling/mail/order_alert/subject.txt
brambling/templates/brambling/mail/order_receipt/subject.txt
brambling/tests/functional/test_invites.py
brambling/tests/functional/test_mailers.py
brambling/tests/functional/test_order_receipt_mailer.py

Fixed the subject.txt files in the mail templates to properly display non-HTML characters in email subject lines.

Subject encoding

---

brambling/templates/brambling/_event_list_item.html

Resolves #417 by using a url tag to point to the event shop view's url, instead of using the event.get_absolute_url method.

Event banner now redirects to event shop page.

---

brambling/forms/orders.py

Fixes #236 by adding a few lines to HostingForm.__init__() in forms/orders.py.

Hosting form city/state/country now defaults to event city/state/country when no prior housing info available.

---

brambling/forms/orders.py
brambling/templates/brambling/event/order/_payment.html
brambling/tests/functional/test_order_forms.py
brambling/tests/integration/test_dwolla.py
brambling/tests/integration/test_stripe.py
brambling/utils/payment.py
brambling/views/orders.py

Fixes error we saw on production site: `'NoneType' object has no attribute 'card'`
Context:
`/var/www/env/src/django-brambling/brambling/forms/orders.py in _post_clean`
```
self <brambling.forms.orders.OneTimePaymentForm object at 0x7fa7bf6e2990>
kwargs
{'amount': Decimal('-94.00'),
'event': <Event: {{name removed}}>,
'order': <Order: Order object>}
```
Other notes:
* If the amount is negative, we can't charge and the form code
assumes that you can charge.
* Setting `self._charge` to `None` by default to mimic the Dwolla
form functionality.  Not totally sure if needed.

Prevent charging stripe if amount is negative.

---

brambling/templates/brambling/event/order/_payment.html

Fixes #762 -- the form was lacking the proper `id` that the discount javascript was looking for.

Fix discount form on payment page

---

brambling/admin/admin.py

This pull request removes the field `additional_editors` from the event admin page. That field was removed from the `Event` model when we revamped the permission system.

Remove obsolete field from event admin.

---

fabfile.py

Adds two tasks for switching between the different deployment tiers we
currently support: `staging` and `production`.  These tasks set values
on `env` according to that particular environment.  At this current
moment it's just the host to run the commands on, but it could be
anything.
This code now requires a tier to be set before running any tasks.  So
you can no longer run tasks with `fab -H <hostname> deploy`, you must
run, e.g., `fab staging deploy`.
Resolves #790.

Implement staging and production tiers for fabric.

---

brambling/views/organizer.py

This pull request adds the permission information for the current user into the `discount_form` view's context. This fixes bug #784 where organizers could not create or update discounts using that form.

Fix discount form permissions

---

brambling/migrations/0053_auto_20160425_2258.py
brambling/models.py
brambling/templates/brambling/event/order/survey.html
brambling/views/orders.py

Fixes issue raised in feedback.
The collect survey data checkbox now explicitly controls only the
built-in questions (how did you hear about it, distribution
promotional materials).  If there is an order form, there will always
be a survey step with that form on it.

Make Order forms always display, regardless of "collect survey data"

---

brambling/filters.py

Based on feedback from organizers. Resolved #801.

Set default ordering for Orders table to 'most recent'

---

brambling/models.py
brambling/tests/functional/test_event_model.py

This seems better thant `string.format()` because (1) we are only using
basic substitutions and (2) we can make those substitutions more safely.
Fixed #807 
Currently, this is backwards compatible with the existing waivers in
the database that use `{bracketed}` syntax.  However, we have to convert
it to `${dollars bracket}` or just `$dollars` syntax to use the Template
class.  That's kind of a shim, so in the future we might want to:
1. Convert existing waivers in the DB to use `$event` and
`$organization`.
2. Change the help text for this field to reflect the above.
But that's not urgent.

Changed liability waiver to use Template.

---

brambling/filters.py
brambling/static/brambling/sass/modules/_event-listing.sass
brambling/static/brambling/sass/styles.sass
brambling/templates/brambling/_event_list_item.html
brambling/templates/brambling/_event_manage_dropdown.html
brambling/templates/brambling/event/order/_masthead.html

This pull request adds: a super-basic dropdown with shortcut links to the different event management areas. Seems like it gets the job done, but could potentially use some bolt-tightening if there's a better way to structure the markup, responsiveize it, give it some visual flair, and so on.
Resolves #327.

Manage event dropdown

---

brambling/static/brambling/sass/modules/_event-listing.sass
brambling/templates/brambling/_event_list_item.html

An attempt at simplifying the dashboard. This would obviate #816. Changes are:
* Removes register/website/facebook/manage buttons from dashboard.
* Moves registration status onto event banner image (where manage button was)
* Makes banner image slightly taller so the whole thing actually displays
* Tightens margins in event metadata (name, date, location)
* Removes date card to cover up less of the banner image
* Removes verbose alerts below event image (since users can be expected to view a specific order to find those details)
* Linkifies event name.

Simplify dashboard

---

brambling/tests/functional/test_webhooks.py
brambling/views/payment.py

The thing we were doing before was not appropriate for class-based
views.  I fixed it using the suggested method from the documentation and
put in a test for this behavior.

Properly exempted Dwolla webhook from CSRF checks

---

brambling/tests/functional/test_organizer_views.py
brambling/views/organizer.py

Resolved #831. Fixed saving of per-attendee notes from organizer order detail page, and added tests proving it.

Fixed attendee notes updating

---

brambling/tests/functional/test_organizer_views.py
brambling/views/organizer.py

Attendees with only transferred items were not showing up in the attendee table view or the exported version of that view. This fixes that issue.

Corrected inclusion of attendees with transferred items in attendee table view

---

.gitignore
.travis.yml
README.rst
requirements.txt
test_project/settings.py

* Make `DATABASE_URL` and `SECRET_KEY` configurable environment variables.
* Clean up settings.py
* Allow for a local_settings.py file that provides per-installation overrides
This PR deliberately does not make any changes to production settings but it does suggestively posit that someday the dev settings might become the production settings.

12 factor dev settings

---

brambling/management/commands/send_daily_emails.py
brambling/models.py
brambling/views/orders.py
test_project/settings.py

Changes `except:` to `except Exception:`, a drop-in replacement that's
safer.
This also fixes flake8 on Circle CI.

Fix newly uncovered flake8 error for bare `except:`

---

brambling/tests/functional/test_attendee_table.py
brambling/tests/unit/test_model_tables.py
brambling/utils/model_tables.py

`purchase_date` was an annotation field, but it was only being added if purchase_date was one of the visible fields. This change makes it so that the annotation is also added if the purchase date ordering is selected, even if the field is not visible. Resolved #877.

Made purchase_date annotation be added if purchase date ordering selected

---

.travis.yml
brambling/templates/brambling/__base.html
brambling/templates/brambling/_stripe_form.html
brambling/templates/brambling/_stripe_js.html
brambling/templates/brambling/creditcard_add.html
brambling/templates/brambling/event/order/summary.html

For PCI compliance and to avoid having to fill out annoying forms every year, we need to switch to using Stripe Elements. This only affects client-side code.
To test this PR:
- Add payment env vars to your dancerfly activate file from 1password
- Create a demo user (email: demo@dancerfly.com)
- Create a demo event (org slug: `demo`; event slug: `demo-event`)
- Create one item for the demo event.
- Connect the demo org to LW stripe account at `/demo/edit/payment/`
- Verify that setting of publishable key is the same, code-wise.
- Verify that, using test API, you are able to save a credit card or get errors from `/billing/`
- Verify that, using test API, you are able to check out for an event both with and without saving the card.

Switched stripe handling to use Stripe Elements

---

brambling/templates/brambling/__base.html

This should improve our ability to view site speed metrics / get suggestions under Behavior > Site Speed > Speed Suggestions - assuming I understand what this does. Here are the docs: https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#siteSpeedSampleRate
Resolved #913

[913] Made site speed sampled 100% of the time

---

brambling/templates/brambling/event/order/hosting.html
brambling/templates/brambling/event/order/shop.html
brambling/templates/brambling/event/order/survey.html
brambling/views/orders.py

This is a standalone first step for #763. It removes discount forms from non-payment pages. This is non-destructive and may potentially resolve some issues folks are having.

Removed discount-related code from non-payment pages

---

brambling/templates/brambling/__base.html
brambling/templates/brambling/dashboard.html
brambling/templates/brambling/organization/detail.html
dancerfly_project/settings.py
dancerfly_project/urls.py

Resolved #918. This was the only hint we had in place. I think we can get rid of it - I suspect that users will already be able to figure out how to use the site. And if we are concerned about the issues this hint seems to be trying to address, we should open tickets to handle them separately. Specifically:

Removed zenaida hints usage

---

Pipfile
Pipfile.lock

Resolved #949. Updated bleach because it was horrendously out of date. This is basically a duplicate of #944 tbh but I had the opportunity to verify that pipenv really doesn't let you just update a single package without re-locking every single non-explicit dependency. So, there are some unrelated package upgrades here but those should just need upgrading once.
I was able to remove html5lib because it's only a dependency of the older bleach version. The newer version instead relies on webencodings.
I chose bleach to start because it is least risky; it's a pretty stable API historically and it is only used for cleaning markdown via the `|markdown` filter.
You can manually test that this doesn't suddenly die by visiting an event detail page and checking that its description renders …

Updated bleach dependency

---

brambling/tests/functional/test_organizer_views.py
brambling/views/organizer.py

Resolved #951. Basically, we had a shim in place for old event URLs but the logic wasn't sufficient to handle the current load of events, and given it's 5 years old I think we can just get rid of it at this point.

#951 Removed old event url shim
